/* js/hallMesh.js — loader and decoder for the arcade's Blender geometry.
 *
 * GENERATED by blender/pack_mesh.py from blender/hallmesh.py. Do not hand-edit:
 * the next export overwrites it. To change a shape, change the factory.
 *
 * Everything on the street used to be built out of axis-aligned boxes in
 * js/arcade.js — the double-parked compact was a slab with a smaller slab on
 * top and four flat stubs for wheels. These are real lofted, bevelled,
 * auto-smoothed meshes with proper split normals.
 *
 * The hall consumes this through `Builder.prototype.model()` in js/arcade.js,
 * which appends a model's triangles into whatever buffer it is building and
 * resolves each vertex's uv against the LIVE atlas rect for its region — the
 * street atlas is shelf-packed at runtime, so a model stores region-relative
 * uv and never a fixed atlas coordinate.
 *
 * Each vertex carries BAKED AMBIENT OCCLUSION in one byte, multiplied into
 * the hall's per-vertex tint channel at build time. That channel already
 * existed and only ever held a per-material constant; now it does the work
 * that makes a surface look lit by a room instead of by a formula.
 *
 * EVERY call site keeps its procedural box rig as a fallback (the house rule
 * from blender/HANDOFF.md 1.5): if the data never arrives, if a region is
 * missing from the atlas, or if `HallMesh.on` is false, the hall builds itself
 * the old way and nothing is ever invisible.
 *
 *   HallMesh.ready()         -> has the payload landed
 *   HallMesh.whenReady(cb)   -> called once, on arrival or on give-up
 *   HallMesh.on()            -> is the geometry usable at all
 *   HallMesh.get(name)       -> decoded model | null
 *   HallMesh.on = () => false  in a harness gives the byte-identical old hall
 */
(function (global) {
  'use strict';

  var DATA = null, state = 'idle', waiting = [], cache = {};
  var SRC = 'js/hallMeshData.js';
  var GIVE_UP_MS = 12000;

  function settle(ok) {
    if (state === 'done' || state === 'failed') return;
    state = ok ? 'done' : 'failed';
    if (ok) DATA = global.__HALL_MESH_DATA__ || null;
    if (!DATA) state = 'failed';
    var w = waiting; waiting = [];
    for (var i = 0; i < w.length; i++) { try { w[i](); } catch (e) { /* never break init */ } }
  }

  function load() {
    if (state !== 'idle') return;
    state = 'loading';
    if (global.__HALL_MESH_DATA__) return settle(true);
    try {
      // Resolve relative to THIS script, so a page served from a subdirectory
      // (or opened from disk) still finds its sibling.
      var here = document.currentScript && document.currentScript.src;
      var url = here ? here.replace(/[^/]*$/, 'hallMeshData.js') : SRC;
      var s = document.createElement('script');
      s.src = url;
      s.async = true;
      s.onload = function () { settle(true); };
      s.onerror = function () { settle(false); };
      document.head.appendChild(s);
      setTimeout(function () { settle(!!global.__HALL_MESH_DATA__); }, GIVE_UP_MS);
    } catch (err) {
      settle(false);
    }
  }

  function decode(b64) {
    var bin = atob(b64), n = bin.length, out = new Uint8Array(n);
    for (var i = 0; i < n; i++) out[i] = bin.charCodeAt(i);
    return out;
  }

  // Decoded lazily per model: the hall may never open, and a street that is
  // never walked should not pay to unpack everything on arrival.
  function get(name) {
    if (cache[name] !== undefined) return cache[name];
    var d = DATA && DATA[name];
    if (!d) { cache[name] = null; return null; }
    try {
      var p = decode(d.p), q = decode(d.q), u = decode(d.u),
        x = decode(d.x), a = decode(d.a), i = decode(d.i);
      cache[name] = {
        n: d.n,
        pos: new Uint16Array(p.buffer, p.byteOffset, d.n * 3),
        nrm: new Int8Array(q.buffer, q.byteOffset, d.n * 3),
        uv: new Uint16Array(u.buffer, u.byteOffset, d.n * 2),
        mat: x,
        ao: a,          // baked occlusion, 255 = fully open
        idx: new Uint16Array(i.buffer, i.byteOffset, d.tri * 3),
        mats: d.m,      // [region, emissive, tint] per material
        lo: [d.b[0], d.b[1], d.b[2]],
        span: [d.b[3], d.b[4], d.b[5]],
      };
    } catch (err) {
      cache[name] = null;   // corrupt payload = fall back, never throw into hall init
    }
    return cache[name];
  }

  global.HallMesh = {
    get: get,
    load: load,
    ready: function () { return state === 'done'; },
    settled: function () { return state === 'done' || state === 'failed'; },
    whenReady: function (cb) {
      if (state === 'done' || state === 'failed') return cb();
      waiting.push(cb);
      load();
    },
    has: function (name) { return !!(DATA && DATA[name]); },
    on: function () { return state === 'done' && !!DATA; },
    names: function () { return DATA ? Object.keys(DATA) : []; },
  };

  // Start immediately but off the critical path: the browser fetches this in
  // parallel with everything else and it is long done before anyone clicks
  // the arcade button. enter() waits on whenReady() only if it somehow isn't.
  if (typeof document !== 'undefined') load();
}(typeof window !== 'undefined' ? window : this));
