# Nugget Cricket commentary: every line in lines.json, in Raju's voice (an Indian cricket commentator from
# the ElevenLabs library, Chris's pick from a tryout page, 2026-10-09) → audio/cricket/vo/ + js/cricketVO.js.
# Key: ~/.config/elevenlabs.key. Unchanged lines are skipped (vo_manifest.json). The big moments get 2 takes.
import os; os.chdir(os.path.dirname(os.path.abspath(__file__)))
import json, re, hashlib, subprocess, urllib.request, concurrent.futures as cf
REPO = os.path.abspath('../..'); OUT = os.path.join(REPO, 'audio', 'cricket', 'vo'); os.makedirs(OUT, exist_ok=True)
KEY = open(os.path.expanduser('~/.config/elevenlabs.key')).read().strip()
VOICE = 'IX4AgWzTnD6q0cNvHqvK'   # Raju – Cricket Match Commentator
lines = json.load(open('lines.json'))
man = json.load(open('vo_manifest.json')) if os.path.exists('vo_manifest.json') else {}
def norm(t): return re.sub(r'\s+', ' ', re.sub(r'[^A-Z0-9 ]+', ' ', t.upper())).strip()
BIG = re.compile(r'SIX|FOUR|MAXIMUM|BOWLED|TIMBER|CAUGHT|TAKEN|RUN OUT|PLUMB|WIN|CROWD|GROUND|HUGE|RACES')
def script(t, take):
    s = t.lower().capitalize()
    s = re.sub(r'([.!?]\s+)([a-z])', lambda m: m.group(1) + m.group(2).upper(), s).replace(' lbw', ' L.B.W.')
    tag = '[shouting]' if BIG.search(t) and t.endswith('!') else '[excited]' if t.endswith('!') else '[calm]'
    if take: tag = '[excited]' if tag == '[shouting]' else '[shouting]' if tag == '[excited]' else tag
    return tag + ' ' + s
jobs = []
for t in lines:
    for take in range(2 if BIG.search(t) else 1):
        tk = norm(t) + ('#' + str(take) if take else ''); text = script(t, take)
        e = man.get(tk)
        if e and e['said'] == text and os.path.exists(os.path.join(OUT, e['file'])): continue
        jobs.append((t, tk, text, 'raju-' + hashlib.sha1((tk + text).encode()).hexdigest()[:8] + '.mp3'))
print(len(jobs), 'clips,', sum(len(j[2]) for j in jobs), 'characters')
def go(j):
    t, tk, text, f = j
    body = json.dumps({'text': text, 'model_id': 'eleven_v3', 'voice_settings': {'stability': 0.0 if '[shouting]' in text else 0.5}}).encode()
    req = urllib.request.Request(f'https://api.elevenlabs.io/v1/text-to-speech/{VOICE}?output_format=mp3_44100_128', data=body, headers={'xi-api-key': KEY, 'Content-Type': 'application/json'})
    with urllib.request.urlopen(req, timeout=120) as r: raw, cost = r.read(), int(r.headers.get('character-cost') or 0)
    tmp = os.path.join(OUT, '_' + f)
    open(tmp, 'wb').write(raw)
    af = 'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.03,areverse,silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.08,areverse,loudnorm=I=-16:TP=-1.5:LRA=11'
    subprocess.run(['ffmpeg', '-v', 'quiet', '-y', '-i', tmp, '-af', af, '-ar', '44100', '-ac', '1', '-b:a', '64k', os.path.join(OUT, f)], check=True); os.remove(tmp)
    d = float(subprocess.run(['ffprobe', '-v', 'quiet', '-show_entries', 'format=duration', '-of', 'csv=p=0', os.path.join(OUT, f)], capture_output=True, text=True).stdout)
    return tk, {'file': f, 'dur': round(d, 2), 'key': norm(t), 'said': text}, cost
total = 0
with cf.ThreadPoolExecutor(3) as ex:
    for tk, e, cost in ex.map(go, jobs): man[tk] = e; total += cost
json.dump(man, open('vo_manifest.json', 'w'), indent=1)
rt = {}
for tk, e in sorted(man.items()): rt.setdefault(e['key'], []).append([e['file'], e['dur']])
with open(os.path.join(REPO, 'js', 'cricketVO.js'), 'w') as f:
    f.write('// ---- 🏏🎙️ NUGGET CRICKET: THE COMMENTARY ---- generated by tools/cricket-audio/render_vo.py (do not hand-edit)\n')
    f.write('// key = normalized line → [[file in audio/cricket/vo/, seconds], …takes]\n')
    f.write('const CRK_VO = ' + json.dumps(rt, separators=(',', ':')) + ';\n')
print('rendered', len(jobs), 'credits', total, 'keys', len(rt))
