"""PACK_MESH — stage 2 of the hall's GEOMETRY pipeline.

    blender/hallmesh.py  --(Blender)-->  render_hall/mesh/*.json
    blender/pack_mesh.py --(this)---->   js/hallMeshData.js

Reads the per-model JSON that hallmesh.export_all() writes and quantizes it
into a compact, no-build-step JS module. Plain Python + numpy, exactly like
pack_atlas.py — run it from anywhere:

    python blender/pack_mesh.py

WHY BASE64 AND NOT JSON NUMBERS: a car is ~3.5k vertices. As decimal text
that is ~400KB; quantized and base64'd it is ~70KB, and it decodes into the
exact typed arrays the hall's vertex buffer wants with no per-number parsing.
Same reasoning as gtaArt.js/hallArt.js shipping their atlases as data URIs —
there is no build step on this site, so the asset has to BE the source file.

THE QUANTIZATION (and why each is safe):
- position -> uint16 across the model's own bounding box. A 2.4m car gets
  0.04mm steps.
- normal   -> int8. Worst case ~1 degree of angular error, i.e. under 2% on a
  Lambert term, in a room lit by neon and bloom. Positions are what you see;
  normals are what you shade with, and shading here is soft.
- uv       -> uint16 over 0..1 of the model's ATLAS REGION (not of the atlas).
  Resolved against the live packer's rect at build time in JS, because the
  street atlas is shelf-packed at runtime and has no fixed coordinates.
- index    -> uint16. A model over 65535 vertices is a bug, not a feature; the
  packer refuses it rather than silently wrapping.

Endianness: every platform that runs a browser is little-endian, and JS typed
arrays follow the host. numpy writes little-endian explicitly ('<') so the
two agree even if this ever runs on something exotic.
"""
import base64
import glob
import gzip
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
IN_DIR = os.path.join(HERE, "render_hall", "mesh")
OUT_JS = os.path.join(REPO, "js", "hallMesh.js")        # loader — HAND-MAINTAINED, never written here
OUT_DATA = os.path.join(REPO, "js", "hallMeshData.js")  # payload, injected async

# Model order in the output = the order the hall wants them; anything found on
# disk that is not listed still ships, appended, so a new model is one export
# away from being available.
ORDER = ["compact", "dill", "crumb", "gravy", "hood", "hen"]


def b64(arr):
    return base64.b64encode(arr.tobytes()).decode("ascii")


def pack_model(d):
    verts = d["verts"]
    tris = d["tris"]
    n = len(verts)
    if n > 65535:
        raise SystemExit("%s: %d vertices exceeds the uint16 index space" % (d["name"], n))
    if n == 0 or not tris:
        raise SystemExit("%s: empty" % d["name"])

    v = np.asarray(verts, dtype=np.float64)
    pos, nrm, uv, mat, ao = v[:, 0:3], v[:, 3:6], v[:, 6:8], v[:, 8], v[:, 9]

    lo = pos.min(axis=0)
    hi = pos.max(axis=0)
    span = np.maximum(hi - lo, 1e-6)
    qp = np.clip(np.rint((pos - lo) / span * 65535.0), 0, 65535).astype("<u2")

    ln = np.maximum(np.linalg.norm(nrm, axis=1, keepdims=True), 1e-9)
    qn = np.clip(np.rint(nrm / ln * 127.0), -127, 127).astype("<i1")

    qu = np.clip(np.rint(np.clip(uv, 0.0, 1.0) * 65535.0), 0, 65535).astype("<u2")
    qm = np.clip(mat, 0, 255).astype("<u1")
    # baked ambient occlusion -> one byte per vertex, multiplied into the
    # material tint at build time. 255 = fully open.
    qa = np.clip(np.rint(np.clip(ao, 0.0, 1.0) * 255.0), 0, 255).astype("<u1")
    qi = np.asarray(tris, dtype=np.int64).reshape(-1).astype("<u2")

    mats = [[m["r"], round(float(m["e"]), 3), round(float(m["t"]), 3)] for m in d["mats"]]
    out = {
        "n": n,
        "tri": len(tris),
        "b": [round(float(x), 5) for x in list(lo) + list(span)],
        "m": mats,
        "p": b64(qp), "q": b64(qn), "u": b64(qu), "x": b64(qm), "a": b64(qa), "i": b64(qi),
    }
    # "v" = the point an ARTICULATED part rotates about, in hall space (§17).
    # It travels with the geometry so js/arcade.js never holds a second copy of
    # a number that is authored in hallmesh.py.
    if d.get("pivot"):
        out["v"] = [round(float(x), 5) for x in d["pivot"]]
    return out, (qp.nbytes + qn.nbytes + qu.nbytes + qm.nbytes + qa.nbytes + qi.nbytes)


DATA_HEADER = '''/* js/hallMeshData.js — the arcade's Blender-authored GEOMETRY, packed.
 *
 * GENERATED by blender/pack_mesh.py from blender/hallmesh.py. Do not hand-edit.
 *
 * This file is NOT in index.html. js/hallMesh.js pulls it in with an async
 * <script> injection after first paint, so several hundred KB of vertex data
 * never sits on the page's critical path — the converter (which is what most
 * visitors actually came for) renders without waiting on the arcade's models.
 *
 * An injected <script> rather than fetch() on purpose: this site is required
 * to work from disk (file://), where fetch is blocked by the origin rules and
 * XHR is unreliable. A script tag has no such problem, needs no CORS, and
 * needs no build step.
 */
window.__HALL_MESH_DATA__ = __DATA__;
'''

HEADER = '''/* js/hallMesh.js — loader and decoder for the arcade's Blender geometry.
 *
 * GENERATED by blender/pack_mesh.py from blender/hallmesh.py. Do not hand-edit:
 * the next export overwrites it. To change a shape, change the factory.
 *
 * Everything on the street used to be built out of axis-aligned boxes in
 * js/arcade.js — the double-parked compact was a slab with a smaller slab on
 * top and four flat stubs for wheels. These are real lofted, bevelled,
 * auto-smoothed meshes with proper split normals.
 *
 * The hall consumes this through `Builder.prototype.model()` in js/arcade.js,
 * which appends a model's triangles into whatever buffer it is building and
 * resolves each vertex's uv against the LIVE atlas rect for its region — the
 * street atlas is shelf-packed at runtime, so a model stores region-relative
 * uv and never a fixed atlas coordinate.
 *
 * Each vertex carries BAKED AMBIENT OCCLUSION in one byte, multiplied into
 * the hall's per-vertex tint channel at build time. That channel already
 * existed and only ever held a per-material constant; now it does the work
 * that makes a surface look lit by a room instead of by a formula.
 *
 * EVERY call site keeps its procedural box rig as a fallback (the house rule
 * from blender/HANDOFF.md 1.5): if the data never arrives, if a region is
 * missing from the atlas, or if `HallMesh.on` is false, the hall builds itself
 * the old way and nothing is ever invisible.
 *
 *   HallMesh.ready()         -> has the payload landed
 *   HallMesh.whenReady(cb)   -> called once, on arrival or on give-up
 *   HallMesh.on()            -> is the geometry usable at all
 *   HallMesh.get(name)       -> decoded model | null
 *   HallMesh.on = () => false  in a harness gives the byte-identical old hall
 */
(function (global) {
  'use strict';

  var DATA = null, state = 'idle', waiting = [], cache = {};
  var SRC = 'js/hallMeshData.js';
  var GIVE_UP_MS = 12000;

  function settle(ok) {
    if (state === 'done' || state === 'failed') return;
    state = ok ? 'done' : 'failed';
    if (ok) DATA = global.__HALL_MESH_DATA__ || null;
    if (!DATA) state = 'failed';
    var w = waiting; waiting = [];
    for (var i = 0; i < w.length; i++) { try { w[i](); } catch (e) { /* never break init */ } }
  }

  function load() {
    if (state !== 'idle') return;
    state = 'loading';
    if (global.__HALL_MESH_DATA__) return settle(true);
    try {
      // Resolve relative to THIS script, so a page served from a subdirectory
      // (or opened from disk) still finds its sibling.
      var here = document.currentScript && document.currentScript.src;
      var url = here ? here.replace(/[^/]*$/, 'hallMeshData.js') : SRC;
      var s = document.createElement('script');
      s.src = url;
      s.async = true;
      s.onload = function () { settle(true); };
      s.onerror = function () { settle(false); };
      document.head.appendChild(s);
      setTimeout(function () { settle(!!global.__HALL_MESH_DATA__); }, GIVE_UP_MS);
    } catch (err) {
      settle(false);
    }
  }

  function decode(b64) {
    var bin = atob(b64), n = bin.length, out = new Uint8Array(n);
    for (var i = 0; i < n; i++) out[i] = bin.charCodeAt(i);
    return out;
  }

  // Decoded lazily per model: the hall may never open, and a street that is
  // never walked should not pay to unpack everything on arrival.
  function get(name) {
    if (cache[name] !== undefined) return cache[name];
    var d = DATA && DATA[name];
    if (!d) { cache[name] = null; return null; }
    try {
      var p = decode(d.p), q = decode(d.q), u = decode(d.u),
        x = decode(d.x), a = decode(d.a), i = decode(d.i);
      cache[name] = {
        n: d.n,
        pos: new Uint16Array(p.buffer, p.byteOffset, d.n * 3),
        nrm: new Int8Array(q.buffer, q.byteOffset, d.n * 3),
        uv: new Uint16Array(u.buffer, u.byteOffset, d.n * 2),
        mat: x,
        ao: a,          // baked occlusion, 255 = fully open
        idx: new Uint16Array(i.buffer, i.byteOffset, d.tri * 3),
        mats: d.m,      // [region, emissive, tint] per material
        lo: [d.b[0], d.b[1], d.b[2]],
        span: [d.b[3], d.b[4], d.b[5]],
      };
    } catch (err) {
      cache[name] = null;   // corrupt payload = fall back, never throw into hall init
    }
    return cache[name];
  }

  global.HallMesh = {
    get: get,
    load: load,
    ready: function () { return state === 'done'; },
    settled: function () { return state === 'done' || state === 'failed'; },
    whenReady: function (cb) {
      if (state === 'done' || state === 'failed') return cb();
      waiting.push(cb);
      load();
    },
    has: function (name) { return !!(DATA && DATA[name]); },
    on: function () { return state === 'done' && !!DATA; },
    names: function () { return DATA ? Object.keys(DATA) : []; },
  };

  // Start immediately but off the critical path: the browser fetches this in
  // parallel with everything else and it is long done before anyone clicks
  // the arcade button. enter() waits on whenReady() only if it somehow isn't.
  if (typeof document !== 'undefined') load();
}(typeof window !== 'undefined' ? window : this));
'''


def main():
    files = sorted(glob.glob(os.path.join(IN_DIR, "*.json")))
    if not files:
        raise SystemExit("no meshes in %s — run hallmesh.export_all() in Blender first" % IN_DIR)
    loaded = {}
    for f in files:
        with open(f) as fh:
            d = json.load(fh)
        loaded[d.get("name") or os.path.splitext(os.path.basename(f))[0]] = d

    names = [n for n in ORDER if n in loaded] + [n for n in sorted(loaded) if n not in ORDER]
    out, total, report = {}, 0, []
    for name in names:
        packed, nbytes = pack_model(loaded[name])
        out[name] = packed
        total += nbytes
        report.append((name, packed["n"], packed["tri"], nbytes))

    body = json.dumps(out, separators=(",", ":"))
    with open(OUT_DATA, "w", newline="\n") as fh:
        fh.write(DATA_HEADER.replace("__DATA__", body))
    # js/hallMesh.js is NOT regenerated here. It used to be, and on the night
    # the boot ledger landed this script silently reverted the loader's
    # HallBoot wiring the next time anyone repacked geometry. The loader is
    # real code with a fallback contract; only the DATA half is generated.
    # (pack_hall.py carries the same rule — see blender/HANDOFF.md §10.)

    print("model            verts    tris    packed")
    for name, n, t, b in report:
        print("  %-14s %6d  %6d  %7.1f KB" % (name, n, t, b / 1024.0))
    print("  %-14s %6s  %6s  %7.1f KB raw" % ("TOTAL", "", "", total / 1024.0))
    for f in (OUT_DATA,):
        with open(f, "rb") as fh:
            gz = len(gzip.compress(fh.read(), 9))
        print("wrote %-24s %7.1f KB  (%.1f KB gzipped)"
              % (os.path.basename(f), os.path.getsize(f) / 1024.0, gz / 1024.0))


if __name__ == "__main__":
    sys.exit(main())
