"""pack_sky.py — the skyline panorama -> js/hallSkyData.js

    blender --background --python blender/skyline.py -- render
    python blender/pack_sky.py [--w 4096] [--h 512]

Stage two of the skyline pipeline (stage one is blender/skyline.py). Takes the
equirectangular RGBA render and writes it as a base64 PNG data URI, plus the
latitude band it covers so the shader's V mapping can never drift from the
camera that produced it.

PNG, NOT JPEG, and not negotiable. The alpha channel IS the silhouette of every
building in the city — JPEG has no alpha, and its block artifacts along a hard
edge would put a halo of half-transparent sky around every roofline. (Same
reason js/hallMapsData.js is a PNG: a block artifact in a normal map becomes
lighting that swims.)

A data URI and not a file: the site must work from disk, and `nugget.png` stays
the repo's only binary art asset.
"""
import base64
import io
import os
import sys

import numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "blender", "render_hall", "sky", "skyline.png")
DST = os.path.join(REPO, "js", "hallSkyData.js")

# Must match blender/skyline.py LAT_MIN / LAT_MAX. Read from the module if it
# imports cleanly (it will not outside Blender — it imports bpy), else the
# literal below, which is checked against the module by the assert in skyline.
LAT = [-4.0, 42.0]


def pack(src=SRC, dst=DST, w=None, h=None):
    im = Image.open(src).convert("RGBA")
    if w or h:
        im = im.resize((w or im.width, h or im.height), Image.LANCZOS)
    a = np.asarray(im)

    # A hard alpha edge resampled by LANCZOS rings — pixels above 255 and below
    # 0 clip, and the ring reads as a bright fringe along every roofline. Clamp
    # the coverage back to a clean step and leave the colour channels soft.
    if w or h:
        a = a.copy()
        a[..., 3] = np.where(a[..., 3] > 118, 255, 0).astype(np.uint8)
        im = Image.fromarray(a)

    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    raw = buf.getvalue()
    b64 = base64.b64encode(raw).decode("ascii")

    cover = float((a[..., 3] > 10).mean())
    lit = float(((a[..., 1] > 30) & (a[..., 3] > 10)).mean())

    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(
            "// GENERATED by blender/pack_sky.py — do not edit.\n"
            "// The Nuggetown skyline as an equirectangular panorama.\n"
            "//\n"
            "// NOT a picture of the sky: R = haze, G = lit-window mask,\n"
            "// B = surface shade, A = silhouette. The palette is still mixed at\n"
            "// runtime from SKY in js/arcade.js, so retuning the night retunes the\n"
            "// city with it. See js/hallSky.js and FS_SKY.\n"
            "//\n"
            "// source : blender/skyline.py (%d x %d, latitude %.1f..%.1f deg)\n"
            "// coverage %.1f%% of the band, %.2f%% lit window pixels\n"
            "// NOT in index.html — js/hallSky.js injects it after first paint.\n"
            "window.__HALL_SKY__ = {\n"
            "  lat: [%.6f, %.6f],\n"
            "  s: '%s',\n"
            "};\n"
            % (im.width, im.height, LAT[0], LAT[1], 100 * cover, 100 * lit,
               np.radians(LAT[0]), np.radians(LAT[1]), b64)
        )
    print("wrote %s  (%d x %d, %d KB png, %d KB js)"
          % (dst, im.width, im.height, len(raw) // 1024, os.path.getsize(dst) // 1024))
    print("     coverage %.1f%%   lit windows %.2f%%" % (100 * cover, 100 * lit))


if __name__ == "__main__":
    argv = sys.argv[1:]
    w = h = None
    if "--w" in argv:
        w = int(argv[argv.index("--w") + 1])
    if "--h" in argv:
        h = int(argv[argv.index("--h") + 1])
    pack(w=w, h=h)
